#!/usr/bin/env python3
"""Build locator-pinned PSID codebook evidence and its adjudication."""

from __future__ import annotations

import argparse
from collections.abc import Sequence
from pathlib import Path

from populace_dynamics.data import psid_questionnaire_inventory as inventory


def _write_or_check(path: Path, rendered: bytes, *, check: bool) -> None:
    if check:
        if not path.is_file():
            raise SystemExit(f"missing committed artifact: {path}")
        if path.read_bytes() != rendered:
            raise SystemExit(
                f"committed artifact differs from source build: {path}"
            )
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(rendered)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    era_ids = [era_id for era_id, _ in inventory.CODEBOOK_ERA_SPECS]
    parser.add_argument(
        "--era",
        action="append",
        choices=era_ids,
        help="build one era; repeat as needed (default: all eras)",
    )
    parser.add_argument(
        "--data-root",
        type=Path,
        default=inventory.default_psid_root(),
        help="PSID staging root (default: ~/PolicyEngine/psid-data)",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data/external/psid_codebook_field_evidence"),
    )
    parser.add_argument(
        "--adjudication-output",
        type=Path,
        default=inventory.default_codebook_adjudication_path(),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="compare generated bytes with committed outputs",
    )
    args = parser.parse_args(argv)

    selected = era_ids if args.era is None else args.era
    if len(selected) != len(set(selected)):
        raise SystemExit("--era cannot repeat the same era")
    artifacts = []
    for era_id in selected:
        artifact = inventory.build_codebook_era_evidence(
            era_id,
            args.data_root,
        )
        artifacts.append(artifact)
        output_path = args.output_dir / f"{era_id}_v1.json"
        _write_or_check(
            output_path,
            inventory.render_codebook_era_evidence(artifact),
            check=args.check,
        )

    if selected == era_ids:
        adjudication = inventory.build_codebook_inventory_adjudication(
            artifacts
        )
        _write_or_check(
            args.adjudication_output,
            inventory.render_codebook_inventory_adjudication(adjudication),
            check=args.check,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
